### ISSUE TITLE
Error invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by wealstarr** [lenmx/migu_music_downloader#3]
Hello,

I'm couple of issues with the app. First is when I search something and a list is generated, when I click the lossless tab to download a popup message "instantly" appears that download completed. Although nothing is downloaded.

Second issue is sometimes, the app when started throws the error _invalid character '<' looking for beginning of value_ and doesn't allow me to use it.
![Report1](https://user-images.githubusercontent.com/26643729/184538558-e9e3891f-66cc-44e7-b287-94ff15151c5d.PNG)

Can you please address these two issues if possible ?

Thanks.

**Comment by lenmx** [comment]
Hello @wealstarr. 
This repository has been abandoned，see [migu music downloader wails](https://github.com/lenmx/migu_music_downloader_wails).
